language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_script:
  - npm install -g mocha
  - cp config.example.js config.js
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fb99b95528fcecfbaf72
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
